### ISSUE TITLE
how to run cuda version use more than one gpu and have a good result

### ISSUE THREAD

**Issue by wangting1995** [UK-MAC/TeaLeaf_CUDA#7]
I  add cuda_device=0,1,2,3  use_cuda_kernels in tea.in file ,i use mpi with four process  to run the tea_leaf,but i found only one gpu  using. can you tell me how to use all gpus with intel mpi in x86 , openmpi in aarch64?

**Comment by douglas-shanks** [comment]
You will want to set `CUDA_VISIBLE_DEVICES ` in your jobscript (or environment if you are running interactively) and not the input file.

**Comment by douglas-shanks** [comment]
A better method to manage affinity would be with a wrapper shell script between srun and the application, that sets CUDA_VISIBLE_DEVICES using SLURM_LOCALID. I'm assuming here that you are using Slurm but of course the same could be done for PBS.
